[build]
  [build.env]
    NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "yt-dlp", "ffmpeg"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"


